### ISSUE TITLE
Extract content from ul/li dl/dt/dd

### ISSUE THREAD

**Issue by bripkens** [pixelastic/html-hierarchy-extractor#1]
I noticed that content from:

```
<ul>
  <li></li>
</ul>
```

and 

```
<dl>
  <dt></dt>
  <dd></dd>
</dl>
```

Is not extracted into the `text` property. Is this by design? It would be great to extract `textContent` in order to support searching through these properties in Algolia.

**Comment by pixelastic** [comment]
Thanks for the comment @bripkens,

By default the library will only extract `p`, but you can configure it by passing an argument object with the key `css_selector` when instanciating it:

```ruby
page = HTMLHierarchyExtractor.new(content, { css_selector: 'p,li,dt,dd' })
```
It will not be able to understand that `dd` is the description of `dt`, though. The header tags are currently [hardcoded](https://github.com/pixelastic/html-hierarchy-extractor/blob/master/lib/html-hierarchy-extractor.rb#L84). I'm open to PR to solve this issue (either by making the header selectors configurable, or allowing a custom hook method to be applied to each extracted element so one can re-assign the hierarchy as needed).

**Comment by bripkens** [comment]
Thank you @pixelastic, this is exactly what I was looking for. An understanding that `dt` is a header is not necessary in my case. And I am not yet sure how users would interpret this.
