### ISSUE TITLE
Depracting this repo in favor of algolia_html_extractor

### ISSUE THREAD

**Issue by pixelastic** [pixelastic/html-hierarchy-extractor#3]
Hello @bripkens, @arakelian, @bdougie, @DuncanAForbes and @ampmtm

I'm pinging you here because you either starred or watched this repo, expressing some interest in it. I wanted to let you know that I'm deprecating this repository in favor of `algolia_html_extractor`.

Rubygems: https://rubygems.org/gems/algolia_html_extractor
GitHub: https://github.com/algolia/html-extractor

The reasons are simple:
- The goal of the gem is tightly coupled with Algolia. Better to have it under this namespace
- The gem will be doing more than just extracting the hierarchy (I plan on adding metadata extraction)
- I should have used underscores in the naming and not dashes anyway :)

All further development will happen on the new gem. I've started a first release of the new gem directly at `v2`, and this gem will stay at `v1` forever. 

The latest release of this gem only add deprecation warnings, prompting users to move to the new gem. If you want to keep using this gem only, you should freeze your dependency to `v1.0.2`.

Thanks for your participation in this repo!

**Comment by bripkens** [comment]
Thank you for this ping @pixelastic. Greatly appreciated! Noted this in our internal tracker :).

**Comment by arakelian** [comment]
Thank you @pixelastic
